from fpdf import FPDF
import datetime
import os

class RCReport(FPDF):
    def header(self):
        # Logo
        template_dir = os.path.dirname(__file__)
        logo_path = os.path.join(template_dir, "logo.png")
        if os.path.exists(logo_path):
            self.image(logo_path, 10, 8, 33)
        
        self.set_font("helvetica", "B", 16)
        self.set_text_color(26, 54, 93) # Navy blue
        self.cell(0, 10, "Structural Calculation Report", border=0, align="R", ln=True)
        
        self.set_font("helvetica", "I", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, "RC Beam Design to BS EN 1992-1-1:2004", border=0, align="R", ln=True)
        
        # Horizontal line
        self.ln(5)
        self.set_draw_color(26, 54, 93)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} - Generated by RC Beam Designer", align="C")

def generate_pdf_report(req_data: dict, res_data: dict, output_path: str):
    """
    Generates a PDF report using fpdf2 (Pure Python).
    """
    pdf = RCReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # --- EXECUTIVE SUMMARY ---
    pdf.set_fill_color(240, 244, 250)
    pdf.rect(10, pdf.get_y(), 190, 45, "F")
    
    pdf.set_font("helvetica", "B", 11)
    pdf.set_text_color(26, 54, 93)
    pdf.cell(0, 10, "  EXECUTIVE SUMMARY", ln=True)
    
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(0)
    
    # Status Row
    pdf.cell(40, 7, "  Overall Status:")
    status = res_data.get("status", "FAIL")
    if status == "PASS":
        pdf.set_text_color(22, 101, 52)
    else:
        pdf.set_text_color(153, 27, 27)
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(55, 7, status)
    
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(0)
    pdf.cell(40, 7, "Max Utilisation:")
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(26, 54, 93)
    pdf.cell(55, 7, f"{res_data.get('utilization_max', 0) * 100:.1f}%")
    pdf.ln(8)
    
    # Data Row
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(0)
    pdf.cell(40, 7, "  Section:")
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(55, 7, f"{req_data.get('b')}x{req_data.get('h')} mm")
    
    pdf.set_font("helvetica", "", 9)
    pdf.cell(40, 7, "Main Steel:")
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(55, 7, f"{req_data.get('n_bars')}-Ø{int(req_data.get('bar_diameter', 0))}")
    pdf.ln(15)

    # Recommendation
    if res_data.get("recommendation"):
        pdf.set_fill_color(247, 249, 252)
        pdf.set_font("helvetica", "I", 9)
        pdf.set_text_color(50, 50, 50)
        pdf.multi_cell(0, 8, f"Recommendation: {res_data['recommendation']['text']}", border=1, fill=True)
        pdf.ln(5)

    # --- 1. DESIGN PARAMETERS ---
    pdf.set_font("helvetica", "B", 11)
    pdf.set_fill_color(232, 237, 245)
    pdf.set_text_color(26, 54, 93)
    pdf.cell(0, 8, " 1. Design Parameters", fill=True, ln=True)
    pdf.ln(2)
    
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(0)
    params = [
        ["Concrete Grade", f"C{req_data['fck']} (fck = {req_data['fck']} MPa)"],
        ["Steel Strength", f"fyk = {req_data['fyk']} MPa"],
        ["Nominal Cover", f"{req_data['cover']} mm"],
        ["Design Moment (MEd)", f"{req_data['MEd']} kNm"],
        ["Design Shear (VEd)", f"{req_data['VEd']} kN"]
    ]
    for row in params:
        pdf.cell(60, 6, row[0])
        pdf.set_font("helvetica", "B", 9)
        pdf.cell(0, 6, row[1], ln=True)
        pdf.set_font("helvetica", "", 9)
    pdf.ln(5)

    # --- CALCULATION STEPS ---
    sections = [
        ("2. Bending Design", "bending"),
        ("3. Shear Design", "shear"),
        ("4. Deflection Check", "deflection"),
        ("5. Cracking Control", "cracking")
    ]
    
    for title, key in sections:
        if pdf.get_y() > 230: pdf.add_page()
        pdf.set_font("helvetica", "B", 11)
        pdf.set_fill_color(232, 237, 245)
        pdf.set_text_color(26, 54, 93)
        pdf.cell(0, 8, f" {title}", fill=True, ln=True)
        pdf.ln(3)
        
        steps = res_data.get("formula_steps", {}).get(key, [])
        for step in steps:
            if pdf.get_y() > 260: pdf.add_page()
            
            pdf.set_font("helvetica", "B", 8)
            pdf.set_text_color(100)
            pdf.cell(0, 4, f"{step['description']}:", ln=True)
            
            pdf.set_font("helvetica", "", 9)
            pdf.set_text_color(26, 54, 93)
            pdf.cell(0, 5, f"  {step['formula']}", ln=True)
            
            pdf.set_text_color(60)
            pdf.cell(0, 5, f"  {step['substitution']}", ln=True)
            
            pdf.set_font("helvetica", "B", 9)
            pdf.set_text_color(22, 101, 52)
            pdf.cell(0, 5, f"  -> {step['result']}", ln=True)
            pdf.ln(2)
        pdf.ln(2)

    # Save
    pdf.output(output_path)
    return True
